development:
  adapter: postgresql
  encoding: unicode
  database: Trivia-Fighter-Leaderboard
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: Trivia-Fighter-Leaderboard
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ENV['DATABASE_URL']
  pool: 5
  timeout: 5000
